added git add -A to yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,8 +63,9 @@ jobs:
         echo "Verifying contents of staticfiles directory..."
         ls -l staticfiles || { echo 'staticfiles directory not found before adding to git'; exit 1; }
         echo "Adding staticfiles..."
-        git add -f staticfiles || { echo "Failed to add staticfiles"; exit 1; }
+        git add -A staticfiles || { echo "Failed to add staticfiles"; exit 1; }
         echo "Committing changes..."
+        git status
         git commit -m "Deploy static files to GitHub Pages" || { echo "Failed to commit changes"; exit 1; }
         echo "Pushing to gh-pages branch..."
         git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages || { echo "Failed to push to gh-pages branch"; exit 1; }
