modified yml by adding static files directory

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,7 +63,7 @@ jobs:
         echo "Verifying contents of staticfiles directory..."
         ls -l staticfiles || { echo 'staticfiles directory not found before adding to git'; exit 1; }
         echo "Adding staticfiles..."
-        git add -A staticfiles || { echo "Failed to add staticfiles"; exit 1; }
+        git add staticfiles/* || { echo "Failed to add staticfiles"; exit 1; }
         echo "Committing changes..."
         git status
         git commit -m "Deploy static files to GitHub Pages" || { echo "Failed to commit changes"; exit 1; }
